const LOCALE = {
    sort: 'sort',
    defaultColor :'All car colors',
    defaultManufactures :'All manufacturers',
    filterSelectMessage :'Please select filter Data',
    filterBtn :'Filter',
    colorLabel:'Color',
    manufacturerLabel:'Manufacturer',
    availableCars:'Availiable Cars',
    showing :'Showing',
    footerText:'AUTO1 Group',
    result:'results',
    linkPurchase:'Purchase',
    linkOrders:'My Orders',
    linkSell:'Sell',
    favourites:"Favourites",
    first:'First',
    previous:'Previous',
    page:'Page',
    of:'of',
    next:'Next',
    last:'Last',
    carAvailiable :'This car is currently available and can be delivered as soon as tomorrow morning. Please be aware that delivery times shown in this page are not definitive and may change due to bad weather conditions.',
    saveFav :'If you like this car, click the button and save it in your collection of favourite items.',
    saveBtn :'Save',
    noSaveFav:'You do not have any favourite car saved. Please visit to',
    viewDetailBtn:'View details',
    localStorageKey:'favoriteCar',
    notFound:'404 -Not found',
    notFoundMessage:"Sorry, the page you are looking for does not exist.",
    notFoundMessage1: "You can always go back to the",

}
module.exports ={
 LOCALE
}